<div class="pb-[40px]">
    <div class="flex flex-col gap-[20px]">
        <h3 class="text-display-24 md:text-display-32 font-semibold">What the Findings Mean for Southeast Asia</h3>
        <div class="flex flex-col gap-[20px] font-light">
            <p class=" text-display-14 md:text-display-16">Southeast Asia has made remarkable progress in reducing poverty and improving food availability over the past three decades. Agricultural modernization, regional economic integration, and investments in rural development have substantially increased food production and reduced undernourishment across many ASEAN Member States. However, the findings of The State of Food Security and Nutrition in the World 2026 (SOFI 2026) indicate that the region is entering a new phase of food security challenges one that extends beyond food availability to ensuring equitable access to affordable, healthy, safe, and sustainable diets (FAO et al. 2026).</p>
            <p class=" text-display-14 md:text-display-16">The challenge is reflected in the region's nutrition profile. Although hunger has generally declined, malnutrition persists in multiple forms. Child stunting and micronutrient deficiencies continue to affect millions of children and women, while overweight, obesity, and diet-related noncommunicable diseases are increasing rapidly due to changing dietary patterns, urbanization, and the growing consumption of highly processed foods (UNICEF, WHO, and World Bank 2025).</p>
            <p class=" text-display-14 md:text-display-16">Climate change further compounds these challenges. Southeast Asia is among the world's most climate-vulnerable regions, with increasing frequency and intensity of floods, droughts, tropical cyclones, sea-level rise, and salinity intrusion threatening agricultural production, fisheries, and rural livelihoods (ADB 2023). Rice-based production systems particularly in the Mekong Delta and major rice-growing areas of Indonesia, the Philippines, Thailand, and Vietnam face increasing production risks that could undermine regional food supplies.</p>
            <p class=" text-display-14 md:text-display-16">Food affordability has also emerged as a defining challenge. SOFI 2026 estimates that 2.69 billion people globally cannot afford a healthy diet (FAO et al. 2026). This finding resonates strongly in Southeast Asia. During the 47th ASEAN Ministers on Agriculture and Forestry (AMAF) Meeting, ASEAN acknowledged that approximately 14% of the region's population continues to experience food insecurity, while 228 million people roughly one-third of Southeast Asia's population cannot afford a healthy diet (FAO 2025). These figures demonstrate that economic growth alone does not guarantee nutritional security and underscore the need for policies that improve both food availability and diet quality.</p>
            <p class=" text-display-14 md:text-display-16">Recognizing these emerging challenges, ASEAN adopted the ASEAN Food, Agriculture and Forestry Sectoral Plan (FAF-SP) 2026–2030, which operationalizes the ASEAN Vision toward 2045. The Plan identifies six strategic priorities: (1) promoting sustainable and regenerative agriculture; (2) enhancing climate resilience; (3) strengthening food and nutrition security; (4) improving market connectivity and competitiveness; (5) fostering innovation, partnerships, and digital transformation; and (6) advancing sustainable forest management (ASEAN 2025).</p>
            <p class=" text-display-14 md:text-display-16">The priorities articulated in SOFI 2026 closely complement ASEAN's regional agenda. Both call for transforming agrifood systems to become more resilient, inclusive, nutrition-sensitive, and environmentally sustainable. This alignment presents an unprecedented opportunity for regional institutions, governments, research organizations, and development partners to work together toward achieving SDG 2 while strengthening resilience against future shocks.</p>
        </div>
    </div>
</div>
